<a href="https://colab.research.google.com/github/codermaker2022/Coffee-cup/blob/main/CleaningData1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
falsy_values=[0,False,None,'',[],{}]

In [3]:
any(falsy_values)

False

In [4]:
np.nan

nan

In [5]:
3+np.nan

nan

In [6]:
a=np.array([1,2,3,np´.nan,4])

SyntaxError: ignored

In [7]:
a=np.array([1,2,3,np.nan,4])

In [8]:
a.sum()

nan

In [9]:
a.std()

nan

In [10]:
a.mean()

nan

In [14]:
a=np.array([1,2,3,np.nan,None,4], dtype='float')

In [15]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [16]:
a.info()

AttributeError: ignored

In [17]:
a.mean()

nan

In [18]:
a.sum()

nan

In [19]:
np.inf

inf

In [20]:
3 + np.inf

inf

In [21]:
np.ind/5

AttributeError: ignored

In [22]:
np.inf/5

inf

In [23]:
np.inf/np.inf

nan

In [24]:
b=np.array([1,2,3,np.inf,np.nan,4], dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """Entry point for launching an IPython kernel.


In [25]:
b=np.array([1,2,3,np.inf,np.nan,4], dtype=np.float64)

In [26]:
b.sum()

nan

In [27]:
np.isnan(np.nan)

True

In [28]:
np.isinf(np.inf)

True

In [29]:
np.isfinite(np.nan), np.isfinite(np.inf)

(False, False)

In [30]:
np.isnan(np.array([1,2,3,np.nan,np.inf,4]))

array([False, False, False,  True, False, False])

In [31]:
np.isnan(np.array([1,2,3,np.nan,np.inf,4])).sum()

1

In [32]:
np.isinf(np.array([1,2,3,np.nan,np.inf,4]))

array([False, False, False, False,  True, False])

In [33]:
np.isfinite(np.array([1,2,3,np.nan,np.inf,4]))

array([ True,  True,  True, False, False,  True])

In [34]:
a=np.array([1,2,3,np.nan,np.nan,4])

In [35]:
a[~np.isnan(a)]

array([1., 2., 3., 4.])

In [36]:
a[np.isfinite(a)]

array([1., 2., 3., 4.])

In [37]:
a[np.isfinite(a)].sum()

10.0

In [39]:
a[np.isfinite(a)].mean()

2.5

In [40]:
a[np.isfinite(a)].std()

1.118033988749895

In [46]:
pd.isnull(np.nan)

True

In [47]:
pd.isnull(np.inf)

False

In [48]:
pd.isnull(np.isinf)

False

In [50]:
pd.isnull(None)

True

In [51]:
pd.isna(np.nan)

True

In [52]:
pd.isna(None)

True

In [53]:
pd.notnull(None)

False

In [54]:
pd.notnull(np.nan)

False

In [56]:
pd.notna(np.nan)

False

In [57]:
pd.notnull(3)

True

In [58]:
pd.isnull(pd.Series([1,np.nan,7]))

0    False
1     True
2    False
dtype: bool

In [59]:
pd.notnull(pd.Series([1,2,np.nan,8]))

0     True
1     True
2    False
3     True
dtype: bool

In [64]:
pd.isnull(pd.DataFrame({
      'Column A':[1,np.nan,7],
      'Column B':[3,5,np.nan],
      'Column C':[7,np.nan,29]
}))

Column A  Column B  Column C
0     False     False     False
1      True     False      True
2     False      True     False

In [65]:
pd.Series([1,2,np.nan]).sum()

3.0

In [66]:
pd.Series([7,9,np.nan]).sum()

16.0

In [67]:
pd.Series([4,3,np.nan]).count()

2

In [68]:
pd.Series([2,3,4,np.nan]).mean()

3.0

In [69]:
s=pd.Series([3,65,5,np.nan,9,np.nan,24])

In [72]:
a

array([ 1.,  2.,  3., nan, nan,  4.])

In [73]:
s

0     3.0
1    65.0
2     5.0
3     NaN
4     9.0
5     NaN
6    24.0
dtype: float64

In [74]:
pd.notnull(s).sum()

5

In [77]:
pd.isnull(s)

0    False
1    False
2    False
3     True
4    False
5     True
6    False
dtype: bool

In [78]:
pd.notnull(s)

0     True
1     True
2     True
3    False
4     True
5    False
6     True
dtype: bool

In [79]:
s[pd.notnull]

0     3.0
1    65.0
2     5.0
4     9.0
6    24.0
dtype: float64

In [80]:
s[pd.notnull].sum()

106.0

In [81]:
s.dropna()

0     3.0
1    65.0
2     5.0
4     9.0
6    24.0
dtype: float64

In [82]:
s

0     3.0
1    65.0
2     5.0
3     NaN
4     9.0
5     NaN
6    24.0
dtype: float64

In [83]:
df = pd.DataFrame({
      'Column A': [1,np.nan,45,56],
      'Column B': [np.nan,8,23,14],
      'Column C': [22,15,2,np.nan],
      'Column D': [90,12,np.nan,5]
})

In [84]:
df

Column A  Column B  Column C  Column D
0       1.0       NaN      22.0      90.0
1       NaN       8.0      15.0      12.0
2      45.0      23.0       2.0       NaN
3      56.0      14.0       NaN       5.0

In [85]:
pd.isnull(df)

Column A  Column B  Column C  Column D
0     False      True     False     False
1      True     False     False     False
2     False     False     False      True
3     False     False      True     False

In [86]:
pd.notnull(df)

Column A  Column B  Column C  Column D
0      True     False      True      True
1     False      True      True      True
2      True      True      True     False
3      True      True     False      True

In [87]:
pd.isnull(df).sum()

Column A    1
Column B    1
Column C    1
Column D    1
dtype: int64

In [88]:
sum(pd.isnull(df).sum())

4

In [89]:
df.shape

(4, 4)

In [90]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Column A  3 non-null      float64
 1   Column B  3 non-null      float64
 2   Column C  3 non-null      float64
 3   Column D  3 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes


In [91]:
df.dropna()

Empty DataFrame
Columns: [Column A, Column B, Column C, Column D]
Index: []

In [92]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [94]:
df2=pd.DataFrame({
        'Column A': [1,np.nan,30],
        'Column B': [2,np.nan,31],
        'Column C': [np.nan,np.nan,100]


})

In [95]:
df2

Column A  Column B  Column C
0       1.0       2.0       NaN
1       NaN       NaN       NaN
2      30.0      31.0     100.0

In [96]:
df.dropna(how='any')

Empty DataFrame
Columns: [Column A, Column B, Column C, Column D]
Index: []

In [98]:
df.dropna(how='all')

Column A  Column B  Column C  Column D
0       1.0       NaN      22.0      90.0
1       NaN       8.0      15.0      12.0
2      45.0      23.0       2.0       NaN
3      56.0      14.0       NaN       5.0

In [99]:
df2.dropna(how='any')

Column A  Column B  Column C
2      30.0      31.0     100.0

In [100]:
df.dropna(thresh=3)

Column A  Column B  Column C  Column D
0       1.0       NaN      22.0      90.0
1       NaN       8.0      15.0      12.0
2      45.0      23.0       2.0       NaN
3      56.0      14.0       NaN       5.0

In [101]:
df.dropna(thresh=2)

Column A  Column B  Column C  Column D
0       1.0       NaN      22.0      90.0
1       NaN       8.0      15.0      12.0
2      45.0      23.0       2.0       NaN
3      56.0      14.0       NaN       5.0

In [102]:
s

0     3.0
1    65.0
2     5.0
3     NaN
4     9.0
5     NaN
6    24.0
dtype: float64

In [103]:
s.fillna(0)

0     3.0
1    65.0
2     5.0
3     0.0
4     9.0
5     0.0
6    24.0
dtype: float64

In [104]:
s.fillna(s.mean())

0     3.0
1    65.0
2     5.0
3    21.2
4     9.0
5    21.2
6    24.0
dtype: float64

In [105]:
s.fillna(method='bfill')

0     3.0
1    65.0
2     5.0
3     9.0
4     9.0
5    24.0
6    24.0
dtype: float64

In [106]:
s.fillna(method='ffill')

0     3.0
1    65.0
2     5.0
3     5.0
4     9.0
5     9.0
6    24.0
dtype: float64

In [107]:
pd.Series([np.nan,3,np.nan,9]).fillna(method='ffill')

0    NaN
1    3.0
2    3.0
3    9.0
dtype: float64

In [108]:
pd.Series([1, np.nan, 3, np.nan, np.nan]).fillna(method='bfill')

0    1.0
1    3.0
2    3.0
3    NaN
4    NaN
dtype: float64

In [109]:
df

Column A  Column B  Column C  Column D
0       1.0       NaN      22.0      90.0
1       NaN       8.0      15.0      12.0
2      45.0      23.0       2.0       NaN
3      56.0      14.0       NaN       5.0

In [110]:
df.fillna({'Column A':0, 'Column B': 77, 'Column C': df['Column C'].mean()})

Column A  Column B  Column C  Column D
0       1.0      77.0      22.0      90.0
1       0.0       8.0      15.0      12.0
2      45.0      23.0       2.0       NaN
3      56.0      14.0      13.0       5.0

In [111]:
df.fillna(method='ffill',axis=0)

Column A  Column B  Column C  Column D
0       1.0       NaN      22.0      90.0
1       1.0       8.0      15.0      12.0
2      45.0      23.0       2.0      12.0
3      56.0      14.0       2.0       5.0

In [112]:
df.fillna(method='ffill',axis=1)

Column A  Column B  Column C  Column D
0       1.0       1.0      22.0      90.0
1       NaN       8.0      15.0      12.0
2      45.0      23.0       2.0       2.0
3      56.0      14.0      14.0       5.0

In [113]:
s.dropna().count()

5

In [114]:
s.count()

5

In [115]:
s 

0     3.0
1    65.0
2     5.0
3     NaN
4     9.0
5     NaN
6    24.0
dtype: float64

In [116]:
len(s)

7

In [117]:
s.count()

5

In [118]:
missing_values = s.count() !=len(s)

In [119]:
missing_values

True